// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class auditLogTable : IMigrationMetadata
    {
        // The immediately following migration contains this historical model plus
        // its Product expiry/unit change. The operations remain explicit here.
        private readonly ResourceManager resources = new ResourceManager(typeof(auditLog));

        string IMigrationMetadata.Id => "202608221104197_auditLogTable";
        string IMigrationMetadata.Source => null;
        string IMigrationMetadata.Target => resources.GetString("Target");
    }
}
