// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class stock : IMigrationMetadata
    {
        private readonly ResourceManager resources = new ResourceManager(typeof(auditLog));

        string IMigrationMetadata.Id => "202608221608150_stock";
        string IMigrationMetadata.Source => null;
        string IMigrationMetadata.Target => resources.GetString("Target");
    }
}
