// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddSaleReceiptSnapshotsAndRevision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSaleReceiptSnapshotsAndRevision));
        
        string IMigrationMetadata.Id
        {
            get { return "202609062110000_AddSaleReceiptSnapshotsAndRevision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
