// <auto-generated />
namespace POS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class fixidentityrole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixidentityrole));
        
        string IMigrationMetadata.Id
        {
            get { return "202608191516350_fix-identity-role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
